# config.yaml
GEMINI_API_KEY: "AIzaSyCtch3XLoQtYSbQuAFiHhuluqrzWr88rH4"
MODEL_NAME: "gemini-2.0-flash" #Variants could be "gemini-2.0-flash-lite", "gemini-2.0-flash", "gemini-2.0-flash-thinking-exp"
ORACLE_HOST: "172.31.100.60"
ORACLE_PORT: 1521
ORACLE_SERVICE_NAME: "persiangulf"
ORACLE_USERNAME: "dodeulbyeol"
ORACLE_PASSWORD: "tong1#pacs1011$"
LONGTERM_PATH: "\\\\172.31.100.60\\Longterm"
LONGTERM_USERNAME: "administrator"
LONGTERM_PASSWORD: "10400"
LOGGING_LEVELS:
  basic: "INFO"
  detailed: "DEBUG"
  error: "ERROR"
ENCAPSULATE_TEXT_AS_ENHANCED_SR: "OFF"
STORE_TRANSCRIBED_REPORT: "OFF"
PRINT_GEMINI_OUTPUT: "ON"