# config.yaml
GEMINI_API_KEY: "AIzaSyCtch3XLoQtYSbQuAFiHhuluqrzWr88rH4"
SR_OUTPUT_FOLDER: "C:\\RaoufSoft\\Spool\\101" #You have to create a register service to listen for DICOM SR files here.
MODEL_NAME: "gemini-2.0-flash" #Variants could be "gemini-2.0-flash-lite", "gemini-2.0-flash", "gemini-2.0-flash-thinking-exp"
ORACLE_HOST: "127.0.0.1"
ORACLE_PORT: 1521
ORACLE_SERVICE_NAME: "persiangulf"
ORACLE_USERNAME: "dodeulbyeol"
ORACLE_PASSWORD: "tong1#pacs1011$"
LONGTERM_USERNAME: "persiangulfadmin"
LONGTERM_PASSWORD: "Raoufsoft1003"
LOGGING_LEVELS:
  basic: "INFO"
  detailed: "DEBUG"
  error: "ERROR"
ENCAPSULATE_TEXT_AS_ENHANCED_SR: "OFF"
STORE_TRANSCRIBED_REPORT: "ON"
PRINT_GEMINI_OUTPUT: "ON"

# ----------------- MongoDB Configuration -----------------
MONGODB_URI: "mongodb://localhost:27017/" # Standard MongoDB connection URI
MONGODB_DATABASE: "audio_transcriber_db" # Name for the database

# ----------------- Network Share Configuration (Optional) -----------------
# Credentials for accessing UNC paths like \\server\share if needed
SHARE_USERNAME: ".\\persiangulfadmin"  # Use double backslash for literal backslash in YAML if needed, or format as needed by WNetAddConnection2
SHARE_PASSWORD: "Raoufsoft1003"