name: google-ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - cx_oracle
  - pip
  - pip:
      - google-generativeai
      - librosa
      - pydicom
      - pynetdicom
      - numpy
      - scipy
      - pyyaml
      - pytest
      - pytest-mock
      - pdfkit
      - watchdog