name: google-ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - oracledb
  - pip
  - pip:
      - google-generativeai
      - librosa
      - pydicom
      - pynetdicom
      - numpy
      - scipy
      - pyyaml
      - watchdog
      - pyinstaller
      - cryptography
