name: google-ai
channels:
  - defaults
  - pytorch
dependencies:
  - python = 3.9
  - pip
  - pip:
      - google-generativeai
      - librosa
      - pydicom
      - pynetdicom
      - cx_oracle
      - numpy
      - scipy
      - pyyaml
      - pytest
      - pytest-mock
      - pdfkit
      - watchdog