name: google-ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - oracledb=2.5.1
  - pip
  - pip:
      - google-generativeai
      - pydicom
      - pynetdicom
      - numpy
      - scipy
      - pyyaml
      - pyinstaller
      - cryptography
      - pywin32