name: google-ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - oracledb=2.5.1 # Oracle DB connectivity
  - pip
  - pip:
      - google-generativeai # Core AI integration
      - pydicom # DICOM processing
      - pynetdicom # DICOM network ops
      - numpy # Audio processing (Reading)
      - scipy # Audio processing (Writing)
      - pyyaml # Config file parsing
      - pyinstaller # Executable packaging
      - cryptography # Security functions
      - pywin32 # Windows integration
      - django~=3.2.0 # Pin Django to version 3.2.x
      - pymongo~=3.12.0 # Pin Pymongo to version 3.12.x
      - djongo # Add Djongo