# Generated by Django 3.2.25 on 2025-04-09 08:59

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('study_key', models.CharField(max_length=255, unique=True)),
                ('dicom_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(default='unknown', max_length=50)),
                ('received_timestamp', models.DateTimeField()),
                ('last_updated_timestamp', models.DateTimeField()),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'studies',
                'ordering': ['-last_updated_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('study_key', models.CharField(max_length=255)),
                ('report_text', models.TextField()),
                ('sr_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('transcription_timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'transcriptions',
                'ordering': ['transcription_timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='transcription',
            index=models.Index(fields=['study_key'], name='transcripti_study_k_bb6fb0_idx'),
        ),
    ]
